name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build PartyMaker APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the code from the Repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install a JDK that is compatible with Android (version 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Step 4: Create local.properties file so build doesn't fail
      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      # Step 5: Create secrets.properties
      - name: Create secrets.properties
        run: |
          echo "MAPS_KEY=${{ secrets.MAPS_KEY }}" > secrets.properties

      # Step 6: Decode google-services.json
      - name: Decode google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json
          echo "Google Services JSON file created"

      # Step 7: Cache Gradle – to speed up runs
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Step 8: Grant permissions to the gradlew file
      - name: Grant permission to execute gradlew
        run: chmod +x ./gradlew

      # Step 9: Running the actual build
      - name: Build with Gradle
        run: ./gradlew assembleDebug
