name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build PartyMaker APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the code from the Repo
      - name: Checkout code
        uses: actions/checkout@v3

        # Step 2: Install a JDK that is compatible with Android (version 17)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

        # Step 3: Cache for Gradle – to speed up runs
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

        # Step 4: Grant permissions to the gradlew file
      - name: Grant permission to execute gradlew
        run: chmod +x ./gradlew

        # Step 5: Running the actual build
      - name: Build with Gradle
        run: ./gradlew assembleDebug
